name: Code Coverage

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant Gradle execution right
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Code Coverage
        run: |
          ./gradlew check
          ./gradlew jacocoTestReport
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
